apiVersion: v1
kind: Service
metadata:
  labels:
    app: vpromc
  name: vpromc
spec:
  ports:
  - port: 11211
    protocol: TCP
    targetPort: vpromc-port
  selector:
    app: vpromc
  type: ClusterIP

