apiVersion: v1
kind: Service
metadata:
  labels:
    app: vprodb
  name: vprodb
spec:
  ports:
  - port: 3306
    protocol: TCP
    targetPort: vprodb-port
  selector:
    app: vprodb
  type: ClusterIP

