apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vproapp
  name: vproapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vproapp
  template:
    metadata:
      labels:
        app: vproapp
    spec:
      containers:
      - image: vprofile/vprofileapp:V1
        name: vprofileapp
        ports:
        - containerPort: 8080
          name: vproapp-port
      initContainers:
      - name: init-mydb
        image: busybox:1.28
        command: ['sh', '-c', "until nslookup vprodb; do echo waiting for mydb; sleep 2; done"]
      - name: init-memecache
        image: busybox:1.28
        command: ['sh', '-c', "until nslookup vpromc; do echo waiting for mydb; sleep 2; done"]

