apiVersion: v1
kind: Service
metadata:
  labels:
    app: vproapp-service
  name: vproapp-service
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: vproapp-port
  selector:
    app: vproapp
  type: LoadBalancer